name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: CI=false npm run build

      - name: Install SSH Key
          run: /
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            echo "$SSH_FINGERPRINT" >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
          shell: bash
          env:
            SSH_FINGERPRINT: ${{secrets.SSH_FINGERPRINT}}
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: actions/download-artifact@v2
        with:
          name: assets
      - name: Upload files
        run: rsync --archive --verbose --stats . ${{secrets.SSH_DESTINATION}}
